version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/test_cicd
  - source: package.json
    destination: /home/ubuntu/test_cicd/package.json
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/test_cicd/
    pattern: "**"
    owner: ubuntu
    mode: 700

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root
  AfterInstall:
    - location: scripts/initialize.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
