version: 0.0
os: linux

files:
  - source: /
    destination: /opt/codedeploy-agent/
file_exists_behavior: OVERWRITE

permissions:
  - object: /tmp
    pattern: "**"
    owner: ubuntu
    mode: 700

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root
  AfterInstall:
    - location: scripts/initialize.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
